Switch example from using ImageNameSelector to ImageName
devfile/devfile-web pull request #112
Opened 2023-12-08 15:07 UTC by HunterGerlach

## What does this PR do / why we need it

This PR updates the latest 2 versions (2.2.1 and 2.2.2) of the Inner/Outer loop docs to correct a regression in the example code.

`ImageNameSelector` -> `ImageName`

## PR acceptance criteria

- [ ] Unit Tests
- [ ] E2E Tests
- [x] Documentation
_Update the [sidebar](https://github.com/devfile/devfile-web/tree/main/apps/landing-page#configuring-navigation) if there is a new file added or an existing filename is changed_

## How to test changes / Special notes to the reviewer

Take a look at the latest spec and confirm that the update matches the spec.

2024-01-09 20:22 UTC, Jdubrick approved these changes

2024-01-10 11:45 UTC, thepetk approved these changes
/lgtm

2024-02-29 01:03 UTC, michael-valdron approved these changes
/lgtm

2024-02-29 14:26 UTC, thepetk commented
/retest

2024-03-01 17:48 UTC, HunterGerlach commented
Is this failure something on my end that I need resolve to help get this merged (e.g. missing test)?

2024-03-01 18:50 UTC, michael-valdron commented
> Is this failure something on my end that I need resolve to help get this merged (e.g. missing test)?

Based on the your changes and the errors given I don't believe so, looking at the logs it appears to be likely change(s) in the allocated resources GitHub actions is providing:
```
 [5921:0229/150007.155352:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

Full Log: https://github.com/devfile/devfile-web/actions/runs/8088608076/job/22130064815?pr=112

2024-03-01 18:52 UTC, michael-valdron commented
> Based on the your changes and the errors given I don't believe so, looking at the logs it appears to be likely change(s) in the allocated resources GitHub actions is providing:
> 
> ```
>  [5921:0229/150007.155352:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
> ```
> 
> Full Log: https://github.com/devfile/devfile-web/actions/runs/8088608076/job/22130064815?pr=112

@thepetk @Jdubrick We'll need to open a bug to address this soon.

2024-03-01 19:52 UTC, thepetk commented
> > > Based on the your changes and the errors given I don't believe so, looking at the logs it appears to be likely change(s) in the allocated resources GitHub actions is providing:
> > > ```
> > > You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 26 MB
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Full Log: https://github.com/devfile/devfile-web/actions/runs/8088608076
> > 
> > 
> > @thepetk @Jdubrick We'll need to open a bug to address this soon.
> 
> Opened a bug issue: [devfile/api#1464](https://github.com/devfile/api/issues/1464)

Yeah I agree with @michael-valdron. I've tried also to see if there is any the code, the package.json deps or the ubuntu release  here https://github.com/devfile/devfile-web/pull/116 but it seems we have insufficient resources from github runner.

2024-04-05 18:11 UTC, michael-valdron commented
/needs-rebase

2024-04-05 18:13 UTC, michael-valdron requested changes
Needs rebase to recent changes.

2024-04-05 21:38 UTC, michael-valdron reviewed
Looking into the broken image links reported:

```
-  /home/runner/work/devfile-web/devfile-web/dist/cypress/apps/landing-page-e2e/scr     (1280x720)
     eenshots/app.cy.ts/Docs -- Version 2.0.0 -- Section Get started -- Page Quick st               
     art with Eclipse Che -- has valid links (failed).png                                           
  -  /home/runner/work/devfile-web/devfile-web/dist/cypress/apps/landing-page-e2e/scr     (1280x720)
     eenshots/app.cy.ts/Docs -- Version 2.0.0 -- Section Get started -- Page Developi               
     ng with devfiles -- has valid links (failed).png
```

Some of the images in our guides may no longer exist which is why E2E check is failing.

cc: @HunterGerlach

2024-04-05 21:48 UTC, michael-valdron reviewed
> Looking into the broken image links reported:
> 
> ```
> -  /home/runner/work/devfile-web/devfile-web/dist/cypress/apps/landing-page-e2e/scr     (1280x720)
>      eenshots/app.cy.ts/Docs -- Version 2.0.0 -- Section Get started -- Page Quick st               
>      art with Eclipse Che -- has valid links (failed).png                                           
>   -  /home/runner/work/devfile-web/devfile-web/dist/cypress/apps/landing-page-e2e/scr     (1280x720)
>      eenshots/app.cy.ts/Docs -- Version 2.0.0 -- Section Get started -- Page Developi               
>      ng with devfiles -- has valid links (failed).png
> ```
> 
> Some of the images in our guides may no longer exist which is why E2E check is failing.
> 
> cc: @HunterGerlach

Error message _might_ be misleading here, I think it could be, based on the guides in question, referring to the domain switch of eclipse.org to eclipse.dev and is not satisfied with the redirection response.

2024-04-05 22:03 UTC, michael-valdron commented
> > Looking into the broken image links reported:
> > ```
> > -  /home/runner/work/devfile-web/devfile-web/dist/cypress/apps/landing-page-e2e/scr     (1280x720)
> >      eenshots/app.cy.ts/Docs -- Version 2.0.0 -- Section Get started -- Page Quick st               
> >      art with Eclipse Che -- has valid links (failed).png                                           
> >   -  /home/runner/work/devfile-web/devfile-web/dist/cypress/apps/landing-page-e2e/scr     (1280x720)
> >      eenshots/app.cy.ts/Docs -- Version 2.0.0 -- Section Get started -- Page Developi               
> >      ng with devfiles -- has valid links (failed).png
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Some of the images in our guides may no longer exist which is why E2E check is failing.
> > cc: @HunterGerlach
> 
> Error message _might_ be misleading here, I think it could be, based on the guides in question, referring to the domain switch of eclipse.org to eclipse.dev and is not satisfied with the redirection response.

@HunterGerlach Fixed the links in question and opened a PR against your branch: https://github.com/HunterGerlach/devfile-web/pull/1

2024-04-05 22:41 UTC, michael-valdron commented
Can confirm the eclipse domain change is the cause of the e2e tests failing: https://github.com/HunterGerlach/devfile-web/pull/1#issuecomment-2040721640

2024-05-31 18:52 UTC, michael-valdron commented
This is blocked by devfile/api#1573

2024-07-24 13:38 UTC, Jdubrick commented
https://github.com/devfile/api/issues/1573 has been completed. Once this PR gets a rebase I believe the `E2E` tests should pass.

2025-07-31 19:33 UTC, michael-valdron reviewed
Hi @HunterGerlach,

Was wondering if there is any follow up on fixes? Would try a rebase as I fixed the failures experienced due to the eclipse website domain change: https://github.com/devfile/devfile-web/pull/131

Since this has been open for over a year I'll need a follow up by this time next month, if we don't hear from you by then I'll close this PR as stale.

Thanks!

2025-08-29 18:00 UTC, michael-valdron commented
As there is no follow up, we will assume this PR has gone stale, closing this PR

2025-08-29 18:00 UTC, closed without merging